### ISSUE TITLE
Sample doesn't Run

### ISSUE THREAD

**Issue by kirankumargithub** [Jaspersoft/domain-sample-application#16]
I tried to download this and build the package package com.jaspersoft.jasperserver.dto.adhoc.query.el doesn't exist in any of the jar files.

Is it possible to programatically modify the domain schema, could you please post a sample ?

**Comment by TanyaEf** [comment]
Sorry, but this functionality haven't been released yet so the application is for internal use.

**Comment by kirankumargithub** [comment]
Thank you very much for the reply. Is it possible to update the domain with new schema using REST API (with new schema changes),  . Tried different mechanisms/samples, but no luck. If you’ve a sample that you can share , I will be grateful to you.

Regards,
Kiran

**Comment by TanyaEf** [comment]
Sure I'll try to help you, I don't have answer right now, but I'm looking for available functionality of out REST API

**Comment by kirankumargithub** [comment]
Thank you very much.  We are implementing Jasper Enterprise Edition and we are blocked on this as we dynamically generate the model/schema.

Regards,
Kiran

**Comment by TanyaEf** [comment]
I'm sorry, but there is no way to create domain using new dynamically generated schema. This functionality hasn't been implemented yet. The only way - to use Resource service and upload domain as resource where domain schema is described in xml, like in the example http://community.jaspersoft.com/wiki/how-upload-domain-jasperreports-server-restclient-utilizing-multipart-body-approach-and-post

**Comment by venkatachalama** [comment]
Can we create a schema.xml file programatically using jrs-rest-java-client library.
